//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Peka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postavka
    {
        public int ID { get; set; }
        public decimal Phone { get; set; }
        public int Organ { get; set; }
        public int Tovar { get; set; }
        public int UserID { get; set; }
    
        public virtual Organiz Organiz { get; set; }
        public virtual Tovar Tovar1 { get; set; }
        public virtual VHOD VHOD { get; set; }
    }
}
